Parser

In [77]:
from bs4 import BeautifulSoup
import os
import numpy as np

def remove_items(test_list, item): 
  
    # using list comprehension to perform the task 
    res = [i for i in test_list if i != item] 
    return res 

def extract_list_texts(html):
    soup = BeautifulSoup(html, 'html.parser')
    
    # Find all <ul> or <ol> elements
    lists = soup.find_all(['li'])
    
    extracted_texts = []
    highlight_masks = []
    
    # Extract text from each list item
    for item in lists:
        if (item.get_text() == ""):
            continue
        try:
            item = str(item).split("<li")[1]
            item = BeautifulSoup("<li" + item, "html.parser")
        except:
            pass
            
        mask = np.empty((0,4))
        text = ""
            
        for text_node in item.find_all(text=True):
            parent = text_node.parent
            is_highlighted = 0
            if parent.name == 'code':
                is_highlighted = 1
            elif parent.name == 'mark':
                if ((parent['class'][0] == 'highlight-teal_background') | (parent['class'][0] == 'highlight-blue_background')):
                    is_highlighted = 2
                elif (parent['class'][0] == 'highlight-yellow_background'):
                    is_highlighted = 3
            elif parent.name == 'li':
                is_highlighted = 0
            else:
                continue
            
            for i in range(len(remove_items(text_node.split(" "), ""))):
                arr = np.zeros((1,4))
                arr[0, is_highlighted] = 1
                mask = np.append(mask, arr, axis=0)
            
            text += text_node
        
        if (text):
            extracted_texts.append(text)
            highlight_masks.append(mask)
    
    return extracted_texts, highlight_masks

# Example HTML containing lists with sublists
dir = 'notes'
data = []

for filename in os.listdir(dir):
    filename = os.path.join(dir, filename)
    with open(filename, "r", encoding="utf-8") as f:
        # Parse the HTML
        html = f.read()
        extracted_texts, highlight_masks = extract_list_texts(html)
        # Print the extracted texts
        for i in range(len(extracted_texts)):
            temp = highlight_masks[i].tolist()
            temp.insert(0, extracted_texts[i])
            data.append(temp)
            print(extracted_texts[i])
            print(highlight_masks[i])

/var/folders/4r/zd25n6j10bl55j03sm0w3pbml3xm8p/T/ipykernel_11126/1857203392.py:33: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  for text_node in item.find_all(text=True):


Binary Arithmetic
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]]
Signed Integers
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]]
Can’t simply add lead bit indicating sign because 0 is unsigned and there would be -0
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]
Two’s Complement - Start with the positive number and flip the bits and add one
[[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]
Throw away carry out
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]
Overflow (number is out of range) if carries don’t match
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1

In [80]:
import pandas as pd

df = pd.DataFrame(data)
df.to_csv("data.csv", index=False, header=False)

df = pd.read_csv("data.csv", header=None)
display(df)

0                     1   \
0                                    Binary Arithmetic  [1.0, 0.0, 0.0, 0.0]   
1                                      Signed Integers  [1.0, 0.0, 0.0, 0.0]   
2    Can’t simply add lead bit indicating sign beca...  [1.0, 0.0, 0.0, 0.0]   
3    Two’s Complement - Start with the positive num...  [0.0, 0.0, 1.0, 0.0]   
4                                 Throw away carry out  [1.0, 0.0, 0.0, 0.0]   
..                                                 ...                   ...   
612                                   Search Algorithm  [0.0, 0.0, 1.0, 0.0]   
613          Iterate through string and compare hashes  [0.0, 0.0, 0.0, 1.0]   
614                  If same hash, then compare string  [0.0, 0.0, 0.0, 1.0]   
615                      Else, update hash and iterate  [0.0, 0.0, 0.0, 1.0]   
616                Big O is because of hash collisions  [1.0, 0.0, 0.0, 0.0]   

                       2                     3                     4   \
0    [1.0, 0.0, 0.0, 0.0]                   NaN                   NaN   
1    [1.0, 0.0, 0.0, 0.0]                   NaN                   NaN   
2    [1.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0, 0.0]   
3    [0.0, 0.0, 1.0, 0.0]  [1.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0, 0.0]   
4    [1.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0, 0.0]   
..                    ...                   ...                   ...   
612  [0.0, 0.0, 1.0, 0.0]                   NaN                   NaN   
613  [0.0, 0.0, 0.0, 1.0]  [0.0, 0.0, 0.0, 1.0]  [0.0, 0.0, 0.0, 1.0]   
614  [0.0, 0.0, 0.0, 1.0]  [0.0, 0.0, 0.0, 1.0]  [0.0, 0.0, 0.0, 1.0]   
615  [0.0, 0.0, 0.0, 1.0]  [0.0, 0.0, 0.0, 1.0]  [0.0, 0.0, 0.0, 1.0]   
616  [1.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0, 0.0]   

                       5                     6                     7   \
0                     NaN                   NaN                   NaN   
1                     NaN                   NaN                   NaN   
2    [1.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0, 0.0]   
3    [1.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0, 0.0]   
4                     NaN                   NaN                   NaN   
..                    ...                   ...                   ...   
612                   NaN                   NaN                   NaN   
613  [0.0, 0.0, 0.0, 1.0]  [0.0, 0.0, 0.0, 1.0]                   NaN   
614  [0.0, 0.0, 0.0, 1.0]  [0.0, 0.0, 0.0, 1.0]                   NaN   
615  [0.0, 0.0, 0.0, 1.0]                   NaN                   NaN   
616  [1.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0, 0.0]   

                       8                     9   ...   18   19   20   21   22  \
0                     NaN                   NaN  ...  NaN  NaN  NaN  NaN  NaN   
1                     NaN                   NaN  ...  NaN  NaN  NaN  NaN  NaN   
2    [1.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0, 0.0]  ...  NaN  NaN  NaN  NaN  NaN   
3    [1.0, 0.0, 0.0, 0.0]  [1.0, 0.0, 0.0, 0.0]  ...  NaN  NaN  NaN  NaN  NaN   
4                     NaN                   NaN  ...  NaN  NaN  NaN  NaN  NaN   
..                    ...                   ...  ...  ...  ...  ...  ...  ...   
612                   NaN                   NaN  ...  NaN  NaN  NaN  NaN  NaN   
613                   NaN                   NaN  ...  NaN  NaN  NaN  NaN  NaN   
614                   NaN                   NaN  ...  NaN  NaN  NaN  NaN  NaN   
615                   NaN                   NaN  ...  NaN  NaN  NaN  NaN  NaN   
616                   NaN                   NaN  ...  NaN  NaN  NaN  NaN  NaN   

      23   24   25   26   27  
0    NaN  NaN  NaN  NaN  NaN  
1    NaN  NaN  NaN  NaN  NaN  
2    NaN  NaN  NaN  NaN  NaN  
3    NaN  NaN  NaN  NaN  NaN  
4    NaN  NaN  NaN  NaN  NaN  
..   ...  ...  ...  ...  ...  
612  NaN  NaN  NaN  NaN  NaN  
613  NaN  NaN  NaN  NaN  NaN  
614  NaN  NaN  NaN  NaN  NaN  
615  NaN  NaN  NaN  NaN  NaN  
616  NaN  NaN  NaN  NaN